# Generated by Django 5.1.4 on 2026-07-13 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatroom_created_by_chatroom_slow_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Исчезает в'),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Реакции'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stickers', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_emoji',
            field=models.CharField(default='🟢', max_length=10, verbose_name='Эмодзи-статус'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(default='tic_tac_toe', max_length=50)),
                ('state', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='chat.chatroom')),
                ('current_turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_games', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
