# Generated by Django 5.1.4 on 2026-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='stickers/', verbose_name='Изображение')),
                ('pack', models.CharField(default='default', max_length=50, verbose_name='Пак')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
