# Generated by Django 5.1.4 on 2026-07-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_friendrequest_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание'),
        ),
    ]
