# Generated by Django 5.1.4 on 2026-07-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_avatar_chatroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='Основатель'),
        ),
    ]
